import json
from collections import defaultdict

defined_plots = {
    'bar-counts': [
        'pandas',
        'matplotlib',
        'seaborn',
        'seaborn-objects',
        'plotnine',
        'lets-plot',
        'plotly',
        'hvplot',
        'altair',
        'ggplot',
    ],
    'box-plot': [
        'pandas',
        'matplotlib',
        'seaborn',
        'plotnine',
        'lets-plot',
        'plotly',
        'hvplot',
        'altair',
        'ggplot',
    ],
    'dodged-bar-chart': [
        'pandas',
        'matplotlib',
        'seaborn',
        'seaborn-objects',
        'plotnine',
        'lets-plot',
        'plotly',
        'hvplot',
        'altair',
        'ggplot',
    ],
    'heatmap': [
        'matplotlib',
        'seaborn',
        'plotnine',
        'lets-plot',
        'plotly',
        'hvplot',
        'altair',
        'ggplot',
    ],
    'scatter-plot': [
        'pandas',
        'matplotlib',
        'seaborn',
        'seaborn-objects',
        'plotnine',
        'lets-plot',
        'plotly',
        'hvplot',
        'altair',
        'ggplot',
    ],
    'scatter-plot-with-colors': [
        'matplotlib',
        'seaborn',
        'seaborn-objects',
        'plotnine',
        'lets-plot',
        'plotly',
        'hvplot',
        'altair',
        'ggplot',
    ],
    'scatter-plot-with-facet': [
        'matplotlib',
        'seaborn',
        'seaborn-objects',
        'plotnine',
        'lets-plot',
        'plotly',
        'hvplot',
        'altair',
        'ggplot',
    ],
    'scatter-plot-with-facets': [
        'matplotlib',
        'seaborn',
        'seaborn-objects',
        'plotnine',
        'lets-plot',
        'plotly',
        'hvplot',
        'altair',
        'ggplot',
    ],
    'scatter-plot-with-size': [
        'pandas',
        'matplotlib',
        'seaborn',
        'seaborn-objects',
        'plotnine',
        'lets-plot',
        'plotly',
        'hvplot',
        'altair',
        'ggplot',
    ],
    'scatter-with-regression': [
        'seaborn',
        'plotnine',
        'lets-plot',
        'plotly',
        'ggplot',
    ],
    'simple-histogram': [
        'pandas',
        'matplotlib',
        'seaborn',
        'seaborn-objects',
        'plotnine',
        'lets-plot',
        'plotly',
        'hvplot',
        'altair',
        'ggplot',
    ],
    'stacked-bar-chart': [
        'pandas',
        'matplotlib',
        'seaborn',
        'seaborn-objects',
        'plotnine',
        'lets-plot',
        'plotly',
        'hvplot',
        'altair',
        'ggplot',
    ],
    'stacked-kde': [
        'pandas',
        'matplotlib',
        'seaborn',
        'seaborn-objects',
        'plotnine',
        'lets-plot',
        'plotly',
        'hvplot',
        'altair',
        'ggplot',
    ],
    'stacked-smooth-line-and-scatter': [
        'matplotlib',
        'seaborn',
        'plotnine',
        'lets-plot',
        'plotly',
        'altair',
        'ggplot',
    ],
    'timeseries': [
        'pandas',
        'matplotlib',
        'seaborn',
        'seaborn-objects',
        'plotnine',
        'lets-plot',
        'plotly',
        'hvplot',
        'altair',
        'ggplot',
    ],
}


def test_exist():
    with open("Examples.ipynb") as f:
        nb = json.load(f)

    found = defaultdict(set)
    for cell in nb["cells"]:
        tags = set(cell["metadata"].get("tags") or [])
        if "ex" not in tags:
            continue
        parsed = {t.split(":")[0]: t.split(":")[1] for t in tags if ":" in t}
        found[parsed["name"]].add(parsed["package"])

    assert {k: set(v) for k, v in defined_plots.items()} == dict(found)
